### ISSUE TITLE
SublimeJedi crash on sublime_jedi_docstring

### ISSUE THREAD

**Issue by egalitarian** [srusskih/SublimeJEDI#147]
When executing sublime_jedi_docstring the plugin crashes in Sublime 2.0.2 / SublimeJedi 0.6.8:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./sublime_jedi/helper.py", line 11, in run
AttributeError: 'View' object has no attribute 'close'

The line is:
        self.view.close()

Commenting it fixes the problem but I don't know if it's neeeded for something else.

**Comment by srusskih** [comment]
Should bew replaced on 

```
self.window.focus_view(self.view)
self.window.run_command("close_file")
```

**Comment by eskin** [comment]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./sublime_jedi/helper.py", line 12, in run
AttributeError: 'HelpMessageCommand' object has no attribute 'window'
