### ISSUE TITLE
Go to definition is not working on master

### ISSUE THREAD

**Issue by edelvalle** [srusskih/SublimeJEDI#174]
When I try to go to the definition of something I get this error in the Sublime terminal:

 ```
Jedi - Python autocompletion.sublime_jedi.utils: 2015-04-02 10:25:14,935: ERROR: JediFacade.get_goto failed
Traceback (most recent call last):
  File "daemon.py", line 122, in get
    return getattr(self, 'get_' + action)()
  File "daemon.py", line 128, in get_goto
    return self._goto()
  File "daemon.py", line 209, in _goto
    definitions = self.script.get_definition()
AttributeError: 'Script' object has no attribute 'get_definition'
```

**Comment by crccheck** [comment]
Same, but I get
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sublime_jedi/go_to.py", line 84, in run
  File "./sublime_jedi/utils.py", line 211, in ask_daemon
  File "./sublime_jedi/utils.py", line 121, in __init__
  File "./sublime_jedi/utils.py", line 233, in get_settings
  File "./sublime_jedi/utils.py", line 325, in expand_path
ValueError: zero length field name in format
```
Sublime Text 2, OSX, using system python 2.6 (the line in question is a `'{}'.format(...)`)

**Comment by edelvalle** [comment]
Ohh, I forgot... I'm using build 3083.

**Comment by srusskih** [comment]
Thanks a lot!
Looks like Jedi changed interface a bit :) 
Fixed.
