### ISSUE TITLE
[BUG] on_hover() event triggers on_query_completions()

### ISSUE THREAD

**Issue by deathaxe** [srusskih/SublimeJEDI#211]
I recently found Jedi to print strange tracebacks to console.

It turned out the `ask_deamon()` function which is called by `on_hover()` for the new docstring tooltips somehow triggers the `on_query_completions()` event. The view being passed to the event handler has no valid window attribute which causes the traceback below.

I honestly can't find a reason for this strange behavior.

```python
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Apps\Sublime\Data\Packages\Jedi - Python autocompletion\sublime_jedi\completion.py", line 169, in on_query_completions
    ask_daemon(view, self._show_completions, 'autocomplete', locations[0])
  File "C:\Apps\Sublime\Data\Packages\Jedi - Python autocompletion\sublime_jedi\utils.py", line 209, in ask_daemon
    window_id = view.window().id()
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by deathaxe** [comment]
It seems to be a core bug.

Related with https://github.com/sublimehq/sublime_text/issues/3424
