### ISSUE TITLE
traceback in console on shift-ctrl-g: KeyError: u'\xc0g'

### ISSUE THREAD

**Issue by sunew** [srusskih/SublimeJEDI#215]
Jedi - Python autocompletion.sublime_jedi.utils: 2017-08-04 21:14:28,989: ERROR   : `JediFacade.get_goto` failed
Traceback (most recent call last):
  File "daemon.py", line 130, in get
    return getattr(self, 'get_' + action)()
  File "daemon.py", line 136, in get_goto
    return self._goto()
  File "daemon.py", line 227, in _goto
    definitions = self.script.goto_definitions()
  File "../jedi/api/__init__.py", line 364, in goto_definitions
    definitions = resolve_import_paths(definitions)
  File "../jedi/api/__init__.py", line 338, in resolve_import_paths
    scopes.update(resolve_import_paths(set(s.follow())))
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "../jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "../jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "../jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "../jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "../jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/imports.py", line 231, in sys_path_with_modifications
    sys_path_mod = list(sys_path.sys_path_with_modifications(self._evaluator, self.module))
  File "../jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "../jedi/evaluate/sys_path.py", line 162, in sys_path_with_modifications
    for path in _get_paths_from_buildout_script(evaluator, buildout_script):
  File "../jedi/evaluate/sys_path.py", line 183, in _get_paths_from_buildout_script
    module = cached and cached.module or load(buildout_script)
  File "../jedi/evaluate/sys_path.py", line 178, in load
    p = Parser(evaluator.grammar, source, buildout_script)
  File "../jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "../jedi/parser/pgen2/parse.py", line 105, in parse
    for type, value, prefix, start_pos in tokenizer:
  File "../jedi/parser/__init__.py", line 343, in _tokenize
    typ = token.opmap[value]
KeyError: u'\xc0g'

**Comment by srusskih** [comment]
Could you please update Jedi (the jedi lib) to different version and check if exception still there?

**Comment by sunew** [comment]
See https://github.com/srusskih/SublimeJEDI/issues/214 - it works when updating jedi to 0.10.2 (latest released version at the time of writing)

**Comment by sunew** [comment]
fixed with latest release.
Thank you, @srusskih :)

**Comment by srusskih** [comment]
You are welcome. Thanks for using (:
