### ISSUE TITLE
Unable to load plugin in ST2

### ISSUE THREAD

**Issue by srusskih** [srusskih/SublimeJEDI#241]
```
Reloading plugin /Users/sr/Library/Application Support/Sublime Text 2/Packages/Jedi - Python autocompletion/__init__.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./__init__.py", line 2, in <module>
    from sublime_jedi import *
  File "./sublime_jedi/__init__.py", line 2, in <module>
    from .completion import SublimeJediParamsAutocomplete, Autocomplete
  File "./sublime_jedi/completion.py", line 17, in <module>
    PLUGIN_ONLY_COMPLETION = sublime.INHIBIT_WORD_COMPLETIONS | sublime.INHIBIT_EXPLICIT_COMPLETIONS
AttributeError: 'module' object has no attribute 'INHIBIT_WORD_COMPLETIONS'
```

**Comment by srusskih** [comment]
Reason: 
same package directory was used for ST2 & ST3 editors.
python cached files was created for ST3, because ST3 was called first.

Workaround: 
clean `*.pyc` files in plugin.
