### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by monkeez** [srusskih/SublimeJEDI#75]
I'm getting this error whenever I type anything, no JEDI auto-completion working.

```
Traceback (most recent call last):
  File "X/subprocess.py", line 1090, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 358, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\Mitch\AppData\Roaming\Sublime Text 3\Packages\Jedi - Python autocompetion\sublime_jedi.py", line 180, in on_query_completions
    ask_daemon(view, self.show_completions, 'autocomplete', locations[0])
  File "C:\Users\Mitch\AppData\Roaming\Sublime Text 3\Packages\Jedi - Python autocompetion\sublime_jedi.py", line 59, in ask_daemon
    complete_funcargs=get_settings_param(view, 'auto_complete_function_params', 'all'),
  File "C:\Users\Mitch\AppData\Roaming\Sublime Text 3\Packages\Jedi - Python autocompetion\utils.py", line 127, in start_daemon
    process = subprocess.Popen(sub_args, **sub_kwargs)
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1096, in _execute_child
PermissionError: [WinError 5] Access is denied
```

**Comment by rajwit** [comment]
Hello All,

I'm learning python now and see an issue when try to execute the below python code and see the error message
"PermissionError: [WinError 5] Access is denied'. 
could you please help me to have the below issue sorted out. 

I have already tried to execute by updating the System variables in Environment variables of System properties as below
pythonexe as System variable and value as ;c:\python27   but still it's not working. 

I do see the below comment in this chain 
"set python_interpreter_path as C:/Python27/python.exe" , if this is the work around not sure where exactly I need to do that. 

Please help me. 


from selenium import webdriver
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
binary = FirefoxBinary('C:\\Users\\r628956\\workspace\\MyFirstProject')
driver = webdriver.Firefox(firefox_binary=binary)
#Firefox browser instantiation
#driver = webdriver.Firefox()
#Loading the gmail URL
driver.get('http://gmail.com')
driver.quit()
